IBM/ibm-monitoring-grafana-operator

- deploy/crds/operator.ibm.com_grafanas_crd.yaml
- deploy/crds/operator.ibm.com_v1alpha1_grafana_cr.yaml
- deploy/olm-catalog/ibm-grafana-operator/0.0.1/ibm-grafana-operator.v0.0.1.clusterserviceversion.yaml
- deploy/olm-catalog/ibm-grafana-operator/0.0.1/operator.ibm.com_grafanas_crd.yaml
- pkg/controller/artifacts/entrypoint.go
- pkg/controller/artifacts/grafanaConfig.go
- pkg/controller/artifacts/grafana_crd_entry.go
Fix some typo to make pod running. In the meanwhile, CRD is changed to add Prometheus service name and port parameters.
> make operand pod running

- deploy/olm-catalog/ibm-monitoring-grafana-operator/1.8.1/ibm-grafana-operator.v1.8.1.clusterserviceversion.yaml
- pkg/controller/model/grafana_deployment.go
> add dependency request and add healthcheck dependency annotation

- deploy/operator.yaml
The lint error will be overwritten when creating case bundle
> IBM certification:use latest image

- Makefile
- deploy/olm-catalog/ibm-monitoring-grafana-operator/1.9.2/ibm-monitoring-grafana-operator.v1.9.2.clusterserviceversion.yaml
- deploy/olm-catalog/ibm-monitoring-grafana-operator/1.9.2/monitoringcontroller.cloud.ibm.com_monitoringdashboards_crd.yaml
- deploy/olm-catalog/ibm-monitoring-grafana-operator/1.9.2/operator.ibm.com_grafanas_crd.yaml
- deploy/olm-catalog/ibm-monitoring-grafana-operator/ibm-monitoring-grafana-operator.package.yaml
> add dev channel 1.9.2 to pick image changes missed

- version/version.go
> bump version in version.go

- deploy/olm-catalog/ibm-monitoring-grafana-operator/1.9.2/ibm-monitoring-grafana-operator.v1.9.2.clusterserviceversion.yaml
- deploy/olm-catalog/ibm-monitoring-grafana-operator/ibm-monitoring-grafana-operator.package.yaml
> promote 1.9.2 to beta channel

- deploy/olm-catalog/ibm-monitoring-grafana-operator/ibm-monitoring-grafana-operator.package.yaml
> promote 1.9.2 beta to stable-v1

- Makefile
- common/scripts/.githooks/pre-commit
- common/scripts/push-csv.sh
- deploy/olm-catalog/ibm-monitoring-grafana-operator/2.0.0/ibm-monitoring-grafana-operator.v2.0.0.clusterserviceversion.yaml
- deploy/olm-catalog/ibm-monitoring-grafana-operator/2.0.0/monitoringcontroller.cloud.ibm.com_monitoringdashboards_crd.yaml
- deploy/olm-catalog/ibm-monitoring-grafana-operator/2.0.0/operator.ibm.com_grafanas_crd.yaml
- deploy/olm-catalog/ibm-monitoring-grafana-operator/ibm-monitoring-grafana-operator.package.yaml
- version/version.go
Signed-off-by: dongwangdw <xdragon007@gmail.com>
> add dev channel 2.0.0

- build/dashboards/kubernetes-pod-overview.json
> correct metrics of container memory by removing fake container

- deploy/olm-catalog/ibm-monitoring-grafana-operator/1.10.0/ibm-monitoring-grafana-operator.v1.10.0.clusterserviceversion.yaml
- deploy/operator.yaml
- pkg/controller/model/grafana_deployment.go
> remove product version

- deploy/olm-catalog/ibm-monitoring-grafana-operator/1.10.0/ibm-monitoring-grafana-operator.v1.10.0.clusterserviceversion.yaml
- deploy/operator.yaml
> update operands image

- deploy/olm-catalog/ibm-monitoring-grafana-operator/1.10.0/ibm-monitoring-grafana-operator.v1.10.0.clusterserviceversion.yaml
- deploy/operator.yaml
>  enable operator for multiple architectures and operating systems

- deploy/olm-catalog/ibm-monitoring-grafana-operator/1.10.1/ibm-monitoring-grafana-operator.v1.10.1.clusterserviceversion.yaml
- deploy/operator.yaml
> update grafana proxy image

- deploy/olm-catalog/ibm-monitoring-grafana-operator/1.10.1/ibm-monitoring-grafana-operator.v1.10.1.clusterserviceversion.yaml
- deploy/operator.yaml
> update proxy with new build

- build/Dockerfile
- build/Dockerfile.ppc64le
- build/Dockerfile.s390x
- deploy/olm-catalog/ibm-monitoring-grafana-operator/1.10.1/ibm-monitoring-grafana-operator.v1.10.1.clusterserviceversion.yaml
- deploy/operator.yaml
> update base image and rebuild

- README.md
- deploy/crds/operator.ibm.com_grafanas_crd.yaml
- deploy/olm-catalog/ibm-monitoring-grafana-operator/1.10.3/operator.ibm.com_grafanas_crd.yaml
- go.mod
- pkg/apis/operator/v1alpha1/grafana_types.go
- pkg/controller/artifacts/ocp_appm_config.go
- pkg/controller/grafana/grafana_reconcile.go
> update ocp app monitoring enablement

- deploy/olm-catalog/ibm-monitoring-grafana-operator/1.10.3/ibm-monitoring-grafana-operator.v1.10.3.clusterserviceversion.yaml
- deploy/operator.yaml
> update proxy base image

- README.md
- deploy/olm-catalog/ibm-monitoring-grafana-operator/1.10.3/ibm-monitoring-grafana-operator.v1.10.3.clusterserviceversion.yaml
- deploy/role.yaml
- pkg/controller/grafana/grafana_reconcile.go
- pkg/controller/model/scc.go
1. fix scc issue
2. remove unused code
> fix scc issue

- build/dashboards/kubernetes-monitoring.json
> update cluster monitoring dashboard due to the cadvisor issue for k8s 1.19

- deploy/olm-catalog/ibm-monitoring-grafana-operator/1.10.5/ibm-monitoring-grafana-operator.v1.10.5.clusterserviceversion.yaml
- deploy/olm-catalog/ibm-monitoring-grafana-operator/1.10.5/monitoringcontroller.cloud.ibm.com_monitoringdashboards_crd.yaml
- deploy/olm-catalog/ibm-monitoring-grafana-operator/1.10.5/operator.ibm.com_grafanas_crd.yaml
- deploy/olm-catalog/ibm-monitoring-grafana-operator/ibm-monitoring-grafana-operator.package.yaml
- pkg/controller/grafana/grafana_reconcile.go
- version/version.go
> create v3 channel and bump the version

- deploy/olm-catalog/ibm-monitoring-grafana-operator/1.11.0/ibm-monitoring-grafana-operator.v1.11.0.clusterserviceversion.yaml
- deploy/operator.yaml
> update images except initcontainer and ingress

- deploy/olm-catalog/ibm-monitoring-grafana-operator/1.11.0/ibm-monitoring-grafana-operator.v1.11.0.clusterserviceversion.yaml
- deploy/operator.yaml
> update init container image

- build/dashboards/kubernetes-monitoring.json
> fix regex for cluster filesystem in filesystem metrics qury

- build/dashboards/kubernetes-monitoring.json
> fix regex to include internal cluster support

- pkg/controller/grafana/grafana_reconcile.go
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/44461
> preserve cert-manager added labels

- deploy/olm-catalog/ibm-monitoring-grafana-operator/1.10.5/ibm-monitoring-grafana-operator.v1.10.5.clusterserviceversion.yaml
Fix for : https://github.ibm.com/IBMPrivateCloud/roadmap/issues/45500
> update version to 1.10.5 in csv

- deploy/olm-catalog/ibm-monitoring-grafana-operator/1.10.5/ibm-monitoring-grafana-operator.v1.10.5.clusterserviceversion.yaml
- deploy/operator.yaml
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/45738
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/45762
> 2.5.11 version of icp-management-ingress digest updated

- deploy/olm-catalog/ibm-monitoring-grafana-operator/1.10.5/ibm-monitoring-grafana-operator.v1.10.5.clusterserviceversion.yaml
- deploy/operator.yaml
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/46137
> ingress digest refresh

- deploy/olm-catalog/ibm-monitoring-grafana-operator/1.12.0/ibm-monitoring-grafana-operator.v1.12.0.clusterserviceversion.yaml
- deploy/operator.yaml
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/46533
> operand auto-sha update

- deploy/olm-catalog/ibm-monitoring-grafana-operator/1.12.0/ibm-monitoring-grafana-operator.v1.12.0.clusterserviceversion.yaml
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/47084
> fix cv linter issue:CSVHasValidRelatedImages

- pkg/controller/model/grafana_router.go
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/46850
> Router container liveness/readiness probe timeout introduced

- deploy/olm-catalog/ibm-monitoring-grafana-operator/1.13.0/ibm-monitoring-grafana-operator.v1.13.0.clusterserviceversion.yaml
- deploy/olm-catalog/ibm-monitoring-grafana-operator/1.13.0/monitoringcontroller.cloud.ibm.com_monitoringdashboards_crd.yaml
- deploy/olm-catalog/ibm-monitoring-grafana-operator/1.13.0/operator.ibm.com_grafanas_crd.yaml
- version/version.go
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/47503
> updated minKubeVersion as 1.19 in operator csv #47503

- deploy/crds/monitoringcontroller.cloud.ibm.com_monitoringdashboards_crd.yaml
- deploy/crds/operator.ibm.com_grafanas_crd.yaml
- deploy/olm-catalog/ibm-monitoring-grafana-operator/1.13.0/monitoringcontroller.cloud.ibm.com_monitoringdashboards_crd.yaml
- deploy/olm-catalog/ibm-monitoring-grafana-operator/1.13.0/operator.ibm.com_grafanas_crd.yaml
- deploy/olm-catalog/ibm-monitoring-grafana-operator/ibm-monitoring-grafana-operator.package.yaml
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/47505
> CRD api movement to v1 changes

- pkg/controller/grafana/grafana_reconcile.go
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/49902
> grafana-operator fails to comeup when enableUserWorkload has null

- deploy/olm-catalog/ibm-monitoring-grafana-operator/1.18.0/ibm-monitoring-grafana-operator.v1.18.0.clusterserviceversion.yaml
- deploy/olm-catalog/ibm-monitoring-grafana-operator/1.18.0/monitoringcontroller.cloud.ibm.com_monitoringdashboards_crd.yaml
- deploy/olm-catalog/ibm-monitoring-grafana-operator/1.18.0/operator.ibm.com_grafanas_crd.yaml
- deploy/olm-catalog/ibm-monitoring-grafana-operator/ibm-monitoring-grafana-operator.package.yaml
- deploy/operator.yaml
- version/version.go
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/50617
> version bump for CS 3.14.0

- deploy/olm-catalog/ibm-monitoring-grafana-operator/1.19.0/ibm-monitoring-grafana-operator.v1.19.0.clusterserviceversion.yaml
- deploy/olm-catalog/ibm-monitoring-grafana-operator/1.19.0/monitoringcontroller.cloud.ibm.com_monitoringdashboards_crd.yaml
- deploy/olm-catalog/ibm-monitoring-grafana-operator/1.19.0/operator.ibm.com_grafanas_crd.yaml
- deploy/olm-catalog/ibm-monitoring-grafana-operator/ibm-monitoring-grafana-operator.package.yaml
- deploy/operator.yaml
- version/version.go
Parent IBMPrivateCloud/roadmap#50617
> bump version for CS 3.15.0

- deploy/olm-catalog/ibm-monitoring-grafana-operator/1.20.0/ibm-monitoring-grafana-operator.v1.20.0.clusterserviceversion.yaml
- deploy/olm-catalog/ibm-monitoring-grafana-operator/1.20.0/monitoringcontroller.cloud.ibm.com_monitoringdashboards_crd.yaml
- deploy/olm-catalog/ibm-monitoring-grafana-operator/1.20.0/operator.ibm.com_grafanas_crd.yaml
- deploy/olm-catalog/ibm-monitoring-grafana-operator/ibm-monitoring-grafana-operator.package.yaml
- deploy/operator.yaml
- version/version.go
For Parent:
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/51961
> bump version for CS CD 3.16.0

- version/version.go
For Parent: https://github.ibm.com/IBMPrivateCloud/roadmap/issues/51897
> Monitoring: Update the Copyright Version

- Dockerfile
- Dockerfile.ppc64le
- Dockerfile.s390x
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/52299
> go version updated to 1.17.7 for eus

- deploy/olm-catalog/ibm-monitoring-grafana-operator/1.21.0/ibm-monitoring-grafana-operator.v1.21.0.clusterserviceversion.yaml
- deploy/olm-catalog/ibm-monitoring-grafana-operator/1.21.0/monitoringcontroller.cloud.ibm.com_monitoringdashboards_crd.yaml
- deploy/olm-catalog/ibm-monitoring-grafana-operator/1.21.0/operator.ibm.com_grafanas_crd.yaml
- deploy/olm-catalog/ibm-monitoring-grafana-operator/ibm-monitoring-grafana-operator.package.yaml
- deploy/operator.yaml
- version/version.go
For Parent: 
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/52606
> bump version for CD 3.17.0

- pkg/controller/grafana/grafana_reconcile.go
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/51656
@pgodowski FYI
> [DONOTMERGE]Notification about OCP app monitoring enabled is removed #51656

- common/config/.hadolint.yml
- deploy/olm-catalog/ibm-monitoring-grafana-operator/1.22.0/ibm-monitoring-grafana-operator.v1.22.0.clusterserviceversion.yaml
- deploy/operator.yaml
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/53265
> updated registry path for operator and operands #53265

- deploy/olm-catalog/ibm-monitoring-grafana-operator/1.23.2/ibm-monitoring-grafana-operator.v1.23.2.clusterserviceversion.yaml
Need to update operator version in latest ltsr CSV 1.23.2
> Fix the version in the latest CSV

- deploy/olm-catalog/ibm-monitoring-grafana-operator/1.25.0/ibm-monitoring-grafana-operator.v1.25.0.clusterserviceversion.yaml
- deploy/olm-catalog/ibm-monitoring-grafana-operator/1.25.0/monitoringcontroller.cloud.ibm.com_monitoringdashboards_crd.yaml
- deploy/olm-catalog/ibm-monitoring-grafana-operator/1.25.0/operator.ibm.com_grafanas_crd.yaml
- deploy/olm-catalog/ibm-monitoring-grafana-operator/ibm-monitoring-grafana-operator.package.yaml
- deploy/operator.yaml
- version/version.go
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/54640
> Monitoring version bump for CS 3.21.0 CD release #54640

- deploy/olm-catalog/ibm-monitoring-grafana-operator/1.23.3/ibm-monitoring-grafana-operator.v1.23.3.clusterserviceversion.yaml
- deploy/olm-catalog/ibm-monitoring-grafana-operator/1.23.3/monitoringcontroller.cloud.ibm.com_monitoringdashboards_crd.yaml
- deploy/olm-catalog/ibm-monitoring-grafana-operator/1.23.3/operator.ibm.com_grafanas_crd.yaml
- deploy/olm-catalog/ibm-monitoring-grafana-operator/ibm-monitoring-grafana-operator.package.yaml
- deploy/operator.yaml
- version/version.go
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/54639
> Monitoring version bump for LTSR 3.19.4release #54639

- deploy/olm-catalog/ibm-monitoring-grafana-operator/1.23.3/ibm-monitoring-grafana-operator.v1.23.3.clusterserviceversion.yaml
- deploy/operator.yaml
> upgrade grafana version from 7.1.5 to 7.5.12 to resolve aqua issue #52360

- deploy/olm-catalog/ibm-monitoring-grafana-operator/1.23.4/ibm-monitoring-grafana-operator.v1.23.4.clusterserviceversion.yaml
- deploy/olm-catalog/ibm-monitoring-grafana-operator/1.23.4/monitoringcontroller.cloud.ibm.com_monitoringdashboards_crd.yaml
- deploy/olm-catalog/ibm-monitoring-grafana-operator/1.23.4/operator.ibm.com_grafanas_crd.yaml
- deploy/olm-catalog/ibm-monitoring-grafana-operator/ibm-monitoring-grafana-operator.package.yaml
- deploy/operator.yaml
- version/version.go
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/54897
> Update operand & operator version in monitoring operator  for LTSR 3.19.5  #54897

- deploy/olm-catalog/ibm-monitoring-grafana-operator/1.23.4/ibm-monitoring-grafana-operator.v1.23.4.clusterserviceversion.yaml
- deploy/operator.yaml
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/54897
> Updated Monitoring operand version for Monitoring LTSR 3.19.5 #54897

- deploy/olm-catalog/ibm-monitoring-grafana-operator/1.26.0/ibm-monitoring-grafana-operator.v1.26.0.clusterserviceversion.yaml
- deploy/olm-catalog/ibm-monitoring-grafana-operator/1.26.0/monitoringcontroller.cloud.ibm.com_monitoringdashboards_crd.yaml
- deploy/olm-catalog/ibm-monitoring-grafana-operator/1.26.0/operator.ibm.com_grafanas_crd.yaml
- deploy/olm-catalog/ibm-monitoring-grafana-operator/ibm-monitoring-grafana-operator.package.yaml
- deploy/operator.yaml
- version/version.go
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/55210
> Version bumpup for monitoring cs cd 3.22.0 #55210

- deploy/olm-catalog/ibm-monitoring-grafana-operator/1.26.0/ibm-monitoring-grafana-operator.v1.26.0.clusterserviceversion.yaml
- deploy/operator.yaml
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/55210
> Update operand version in monitoring operator version bump up cs cd 3.22.0

- deploy/olm-catalog/ibm-monitoring-grafana-operator/1.23.5/ibm-monitoring-grafana-operator.v1.23.5.clusterserviceversion.yaml
- deploy/olm-catalog/ibm-monitoring-grafana-operator/1.23.5/monitoringcontroller.cloud.ibm.com_monitoringdashboards_crd.yaml
- deploy/olm-catalog/ibm-monitoring-grafana-operator/1.23.5/operator.ibm.com_grafanas_crd.yaml
- deploy/olm-catalog/ibm-monitoring-grafana-operator/ibm-monitoring-grafana-operator.package.yaml
- deploy/operator.yaml
- version/version.go
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/55406
> Update operand & operator version in monitoring operator for LTSR 3.19.6 #55406

- deploy/olm-catalog/ibm-monitoring-grafana-operator/1.26.0/ibm-monitoring-grafana-operator.v1.26.0.clusterserviceversion.yaml
- deploy/operator.yaml
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/55210
> Operand version updated for 3.22.0

- deploy/olm-catalog/ibm-monitoring-grafana-operator/1.23.6/ibm-monitoring-grafana-operator.v1.23.6.clusterserviceversion.yaml
- deploy/olm-catalog/ibm-monitoring-grafana-operator/1.23.6/monitoringcontroller.cloud.ibm.com_monitoringdashboards_crd.yaml
- deploy/olm-catalog/ibm-monitoring-grafana-operator/1.23.6/operator.ibm.com_grafanas_crd.yaml
- deploy/olm-catalog/ibm-monitoring-grafana-operator/ibm-monitoring-grafana-operator.package.yaml
- deploy/operator.yaml
- version/version.go
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/55875
> Update operand version for 3.19.7

- deploy/olm-catalog/ibm-monitoring-grafana-operator/1.23.6/ibm-monitoring-grafana-operator.v1.23.6.clusterserviceversion.yaml
- deploy/operator.yaml
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/55875
> Updated Monitoring operand version for Monitoring LTSR 3.19.7

- deploy/olm-catalog/ibm-monitoring-grafana-operator/1.27.0/ibm-monitoring-grafana-operator.v1.27.0.clusterserviceversion.yaml
- deploy/olm-catalog/ibm-monitoring-grafana-operator/1.27.0/monitoringcontroller.cloud.ibm.com_monitoringdashboards_crd.yaml
- deploy/olm-catalog/ibm-monitoring-grafana-operator/1.27.0/operator.ibm.com_grafanas_crd.yaml
- deploy/olm-catalog/ibm-monitoring-grafana-operator/ibm-monitoring-grafana-operator.package.yaml
- deploy/operator.yaml
- version/version.go
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/56047
> Operand and operator version bump up for 3.23.0

- deploy/olm-catalog/ibm-monitoring-grafana-operator/1.27.0/ibm-monitoring-grafana-operator.v1.27.0.clusterserviceversion.yaml
- deploy/operator.yaml
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/56047
> Operand version update for monitoring 3.23.0 #56047

- deploy/olm-catalog/ibm-monitoring-grafana-operator/1.23.7/ibm-monitoring-grafana-operator.v1.23.7.clusterserviceversion.yaml
- deploy/olm-catalog/ibm-monitoring-grafana-operator/1.23.7/monitoringcontroller.cloud.ibm.com_monitoringdashboards_crd.yaml
- deploy/olm-catalog/ibm-monitoring-grafana-operator/1.23.7/operator.ibm.com_grafanas_crd.yaml
- deploy/olm-catalog/ibm-monitoring-grafana-operator/ibm-monitoring-grafana-operator.package.yaml
- deploy/operator.yaml
- version/version.go
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/56315
> Operand and operator version update for monitoring 3.19.8 #56315

- deploy/olm-catalog/ibm-monitoring-grafana-operator/1.28.0/ibm-monitoring-grafana-operator.v1.28.0.clusterserviceversion.yaml
- deploy/olm-catalog/ibm-monitoring-grafana-operator/1.28.0/monitoringcontroller.cloud.ibm.com_monitoringdashboards_crd.yaml
- deploy/olm-catalog/ibm-monitoring-grafana-operator/1.28.0/operator.ibm.com_grafanas_crd.yaml
- deploy/olm-catalog/ibm-monitoring-grafana-operator/ibm-monitoring-grafana-operator.package.yaml
- deploy/operator.yaml
- version/version.go
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/56850
> operand and operator version bumup for 3.24.0 #56850

- deploy/olm-catalog/ibm-monitoring-grafana-operator/1.23.7/ibm-monitoring-grafana-operator.v1.23.7.clusterserviceversion.yaml
- deploy/operator.yaml
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/56315
> operand version bumup in operator for 3.19.8 #56315

- Makefile
- build/Dockerfile
- build/Dockerfile.ppc64le
- build/Dockerfile.s390x
- common/config/.hadolint.yml
- common/scripts/config_docker.sh
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/56862
> Artifactory image location updated for Monitoring #56862

- deploy/olm-catalog/ibm-monitoring-grafana-operator/1.27.1/ibm-monitoring-grafana-operator.v1.27.1.clusterserviceversion.yaml
- deploy/operator.yaml
https://github.ibm.com/IBMPrivateCloud/roadmap/issues/56850
> operand version bumpup for monitoring 3.23.1 #56850
